import './globals.css';
import localFont from 'next/font/local';

const myFont = localFont({ src: './fonts/ChosunGu.ttf', variable: '--font-Chosun' });

export const metadata = {
    title: 'gift-checker',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='ko' className={myFont.className}>
            <body className='font-chosun'>{children}</body>
        </html>
    );
}
