import './globals.css';

export const metadata = {
    title: 'gift-checker',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            {/* <body className={inter.className}>{children}</body> */}
            <body>{children}</body>
        </html>
    );
}
